feature/team
cslant/laravel-telegram-git-notifier pull request #75
Opened 2024-05-15 11:17 UTC by hokhacminhtri

Add team event.
Result:
- added_to_repository
![image](https://github.com/cslant/laravel-telegram-git-notifier/assets/57437836/470b6539-7708-465f-9bf1-56e90603029f)
- created
![image](https://github.com/cslant/laravel-telegram-git-notifier/assets/57437836/ca3fef6d-361a-4a03-8ca6-6e94197d8016)
- deleted
![image](https://github.com/cslant/laravel-telegram-git-notifier/assets/57437836/83ba0e48-7e69-4a68-8f13-3113216be965)
- removed_from_repository
![image](https://github.com/cslant/laravel-telegram-git-notifier/assets/57437836/581cd9b1-8bf7-45ca-b5cb-73d45da6e1e0)

2024-05-16 10:21 UTC, tanhongit commented on resources/views/events/github/team/added_to_repository.blade.php
> +🔐 {!! __('tg-notifier::events/github/team.added_to_repository.permissions') !!}: <b>{{ "{\n" . collect((array) $payload->repository->permissions)->filter()->map(fn($v, $k) => "    \"$k\": " . ($v ? '
@hokhacminhtri what do you think about only displaying the highest permission, not the list?

2024-05-16 10:49 UTC, hokhacminhtri commented on resources/views/events/github/team/added_to_repository.blade.php
> +🔐 {!! __('tg-notifier::events/github/team.added_to_repository.permissions') !!}: <b>{{ "{\n" . collect((array) $payload->repository->permissions)->filter()->map(fn($v, $k) => "    \"$k\": " . ($v ? '
@tanhongit Good suggestion, I'll update.

2024-05-16 18:33 UTC, tanhongit commented on resources/views/events/github/team/added_to_repository.blade.php
> +🔐 {!! __('tg-notifier::events/github/team.added_to_repository.permissions') !!}: <b>{{ "{\n" . collect((array) $payload->repository->permissions)->filter()->map(fn($v, $k) => "    \"$k\": " . ($v ? '
thanks!

2024-05-18 09:41 UTC, tanhongit requested changes

2024-05-18 09:41 UTC, tanhongit commented on resources/views/events/github/team/added_to_repository.blade.php
> +🔐 {!! __('tg-notifier::events/github/team.added_to_repository.permissions') !!}: <b>{{ "{\n" . collect((array) $payload->repository->permissions)->filter()->map(fn($v, $k) => "    \"$k\": " . ($v ? '
@hokhacminhtri I created some tests, you just need to get the first permission name if it is true.

![image](https://github.com/cslant/laravel-telegram-git-notifier/assets/35853002/401f0068-3127-4b41-a7e6-fc5d4b130466) ![image](https://github.com/cslant/laravel-telegram-git-notifier/assets/35853002/61fd2a02-61af-487f-b778-47055c151e71) ![image](https://github.com/cslant/laravel-telegram-git-notifier/assets/35853002/212d7528-3529-4517-a65b-db0aeb1347a2)

2024-05-18 09:58 UTC, tanhongit commented on resources/views/events/github/team/added_to_repository.blade.php
> +🔐 {!! __('tg-notifier::events/github/team.added_to_repository.permissions') !!}: <b>{{ "{\n" . collect((array) $payload->repository->permissions)->filter()->map(fn($v, $k) => "    \"$k\": " . ($v ? '
I checked the message and saw that we already showed the role, so I think there's no need to show the permission anymore, maybe it's not necessary. If you still want to display then there is no problem with this action anymore
![image](https://github.com/cslant/laravel-telegram-git-notifier/assets/35853002/bcbb90f4-7641-4eed-b265-83971ca083a9)

2024-05-18 09:58 UTC, tanhongit commented on resources/views/events/github/team/deleted.blade.php
> +⚡ <b>{!! __('tg-notifier::events/github/team.deleted.title') !!}</b> 🎊
Can you please change the trash icon for this line?

```suggestion
🗑 <b>{!! __('tg-notifier::events/github/team.deleted.title') !!}</b> 🎊
```

2024-05-20 10:58 UTC, hokhacminhtri commented on resources/views/events/github/team/added_to_repository.blade.php
> +🔐 {!! __('tg-notifier::events/github/team.added_to_repository.permissions') !!}: <b>{{ "{\n" . collect((array) $payload->repository->permissions)->filter()->map(fn($v, $k) => "    \"$k\": " . ($v ? '
Updated. Please help me check it. Thanks.

2024-05-20 11:32 UTC, tanhongit approved these changes
thanks for all @hokhacminhtri

2024-05-20 11:32 UTC, merged